# Generated by Django 3.1.1 on 2020-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.AddField(
            model_name='menu',
            name='large',
            field=models.CharField(default=0, max_length=45),
        ),
        migrations.AddField(
            model_name='menu',
            name='primaryKey',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='small',
            field=models.CharField(default=0, max_length=45),
        ),
        migrations.AlterField(
            model_name='menu',
            name='pizza',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
