# Generated by Django 3.1.1 on 2020-10-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201027_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='id',
        ),
        migrations.AddField(
            model_name='toppings',
            name='charges',
            field=models.CharField(default=0, max_length=45),
        ),
        migrations.AddField(
            model_name='toppings',
            name='primaryKey',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
